In [6]:
import numpy as np
from statistics import mean

In [3]:
pointToCluster = {(1, 1): 0, (2, 1): 0, (7, 2): 0, (8, 1): 0, (9, 1): 0}

In [5]:
points = list(pointToCluster.keys())

In [9]:
xVals = [xy[0] for xy in points]
print(xVals)
mean(xVals)

[1, 2, 7, 8, 9]


5.4

In [10]:
yVals = [xy[1] for xy in points]
print(yVals)
mean(yVals)

[1, 1, 2, 1, 1]


1.2

In [11]:
a = np.array(points)
a

array([[1, 1],
       [2, 1],
       [7, 2],
       [8, 1],
       [9, 1]])

In [14]:
meanArr = np.array([mean(xVals), mean(yVals)])
meanArr

array([5.4, 1.2])

In [16]:
centered = a - meanArr
centered

array([[-4.4, -0.2],
       [-3.4, -0.2],
       [ 1.6,  0.8],
       [ 2.6, -0.2],
       [ 3.6, -0.2]])

In [22]:
centered_T = np.transpose(centered)
centered_T

array([[-4.4, -3.4,  1.6,  2.6,  3.6],
       [-0.2, -0.2,  0.8, -0.2, -0.2]])

In [24]:
M = np.matmul(centered_T, centered)
M

array([[53.2,  1.6],
       [ 1.6,  0.8]])

In [27]:
ci = (1/len(points)) * M 
ci

array([[10.64,  0.32],
       [ 0.32,  0.16]])

In [35]:
x_values, y_values = zip(*points)
covdata = np.vstack((x_values, y_values))
covdata

array([[1, 2, 7, 8, 9],
       [1, 1, 2, 1, 1]])

In [34]:
thisClustersCOV = np.cov(covdata)
thisClustersCOV

array([[13.3,  0.4],
       [ 0.4,  0.2]])

In [38]:
thisClustersCOV = np.cov(centered.T, bias=True)
thisClustersCOV

array([[10.64,  0.32],
       [ 0.32,  0.16]])